repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      - id: uv-lock
        
  - repo: local
    hooks:
      - id: uv-ruff
        name: uv-ruff
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push] # Run ruff on push, not every commit, to save time
      
      - id: uv-pylint
        name: uv-pylint
        entry: uv run pylint .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push] # Run pylint on push, not every commit, to save time
      
      - id: uv-mypy
        name: uv-mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push] # Run mypy on push, not every commit, to save time
      
      - id: uv-pytest
        name: uv-pytest
        entry: uv run pytest .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push] # Run tests on push, not every commit, to save time