[project]
name = "notion-migration"
version = "0.1.0"
description = ""
authors = [
    {name = "Reza Saidafkan",email = "93768131+rsaidafk@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "notion-client (>=2.5.0,<3.0.0)",
    "dataclasses-json (>=0.6.7,<0.7.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "types-python-dateutil (>=2.9.0.20251008,<3.0.0.0)",
    "pydantic (>=2.12.4,<3.0.0)",
    "aiolimiter (>=1.2.1,<2.0.0)",
]

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "py-spy (>=0.4.1,<0.5.0)",
    "mypy (>=1.19.1,<2.0.0)",
    "ruff (>=0.14.13,<0.15.0)",
    "pylint (>=4.0.4,<5.0.0)",
]

[tool.poetry]
packages = [{include = "notion_migration", from = "src"}]

[tool.ruff.lint]
# Enable Pylint (PL), Docstrings (D), and Import Sorting (I)
select = [
    "E", "F",     # Default Flake8 rules
    "PL",         # Pylint-inspired rules (covers R0903, C0103, etc.)
    "D",          # pydocstyle (covers C0114, C0115, C0116)
    "I",          # isort (covers C0411 import order)
]

ignore = [
    "D102",  # Ignore missing docstring in public methods
    "D103",  # Ignore missing docstring in public functions
    "D101",  # Ignore missing docstring in public class
    "D100",  # Ignore missing docstring in public module
    "D104",  # Ignore missing docstring in public package
    "D107",  # Ignore missing docstring in `__init__` method
    "D105",  # Missing docstring in magic method
    "E501",  # Line too long (handled by Pylint)
]

exclude = [
    "build",
    "dist",
    ".venv",
    "__pypackages__",
    "dev/**",
    "**/tests/**",
]

[tool.ruff.lint.pydocstyle]
convention = "google" # Or "numpy" / "pep257"

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
]
ignore = ["dev"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
