[project]
name = "notion-migration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "packages/common-libs",
    "apps/migration-engine",
    "apps/tracing",
]

[tool.ruff.lint]
# Enable Pylint (PL), Docstrings (D), and Import Sorting (I)
select = [
    "E", "F",     # Default Flake8 rules
    "PL",         # Pylint-inspired rules (covers R0903, C0103, etc.)
    "D",          # pydocstyle (covers C0114, C0115, C0116)
    "I",          # isort (covers C0411 import order)
    "W",          # For pycodestyle warnings/whitespace
]

ignore = [
    "D102",  # Ignore missing docstring in public methods
    "D103",  # Ignore missing docstring in public functions
    "D101",  # Ignore missing docstring in public class
    "D100",  # Ignore missing docstring in public module
    "D104",  # Ignore missing docstring in public package
    "D107",  # Ignore missing docstring in `__init__` method
    "D105",  # Missing docstring in magic method
    "E501",  # Line too long (handled by Pylint)
    "D205",  # 1 blank line required between summary line and description
]

exclude = [
    "build",
    "dist",
    ".venv",
    "__pypackages__",
    ".dev",
    ".dev/**",
    "**/tests/**",
]

[tool.ruff.format]
# Ensure the formatter is using the same logic
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true # This allows the formatter to wrap docstrings that exceed line-length

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
]

ignore = [
    "build",
    "dist",
    ".venv",
    "__pypackages__",
    ".dev",
    ".dev/**",
    "**/tests/**"
]

[tool.pylint.master]
# This tells Pylint to completely skip these directories
ignore-paths = [
    "^.*/tests/.*$",
    "^tests/.*$"
]