[project]
name = "tracing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Reza Saidafkan", email = "93768131+rsaidafk@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.2",
    "common-libs",
    "sqlmodel>=0.0.37",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "freezegun>=1.5.1",
    "pytest-asyncio>=0.23.7",
]

[tool.uv.sources]
common-libs = { workspace = true }

[tool.uv]
package = true
