name: CI
on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define your workspace members here
        package: [migration-engine, tracing, common-libs]

    steps:
      - uses: actions/checkout@v6
          
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      
      - name: Set up Python
        run: uv python install
      
      - name: synchornize dependencies
        run: uv sync --all-packages
      
      - name: uv ruff check
        run: uv run --project ${{ matrix.package }} ruff check .

      - name: uv mypy check
        run: uv run --project ${{ matrix.package }} mypy .
      
      - name: uv pylint check
        run: uv run --project ${{ matrix.package }} pylint .

      - name: Run Tests with pytest
        run: uv run --project ${{ matrix.package }} pytest